---
title: "Data Visualization"
author: "Anna Poulton"

format:
  html:
    code-fold: true
    code-summary: "Show code"
    embed-resources: true
execute:
  warning: false
  message: false
---

# Set-up

## Load Packages
```{r}
### Data wrangling
library(readr)
library(here)      ### for robust relative file paths
library(dplyr)
library(tidyr)
library(forcats)   ### tools for working with factors (e.g., reordering)
library(janitor)   ### clean column names

### Visualization
library(ggplot2)

### Interactive output
library(plotly)
library(DT)
library(leaflet)
```


## Read in data
```{r}
delta_visits_raw = read_csv(here('data/Socioecological_monitoring_data.csv'))

```

## Explore data

```{r}
colnames(delta_visits_raw)
str(delta_visits_raw)
glimpse(delta_visits_raw)
```

## Clean data

```{r}
delta_visits = delta_visits_raw %>%
               janitor::clean_names()
delta_visits
```


```{r}
visits_long = delta_visits %>% 
              pivot_longer(cols = c(sm_boat, med_boat, lrg_boat, bank_angler, scientist, cars),
                           names_to = "visitor_type",
                           values_to = "quantity") %>%
              rename(restore_loc = eco_restore_approximate_location) %>%
              select(-notes)
glimpse(visits_long)
```


```{r}
daily_visits_long = visits_long %>% group_by(restore_loc, date, visitor_type) %>%
                                    summarize(daily_visits = sum(quantity), .groups = "drop")
glimpse(daily_visits_long)
```


# Visualization


```{r}
ggplot(data = daily_visits_long) + 
  geom_col(aes(x = restore_loc, y = daily_visits)) + 
  labs(title = "title") 
```


```{r}
daily_visits_long %>% 
  filter(daily_visits < 30, 
         visitor_type %in% c("sm_boat", "med_boat", "lrg_boat")) %>%
  ggplot() +
  geom_boxplot(aes(x = visitor_type, y = daily_visits))
```


```{r}
daily_visits_totals <- daily_visits_long %>%
  group_by(restore_loc) %>%
  mutate(total = sum(daily_visits)) %>%
  ungroup() %>%
  mutate(restore_loc = fct_reorder(restore_loc, desc(total)))

unique(daily_visits_totals$restore_loc)

facet_plot <- ggplot(data = daily_visits_totals,
       aes(x = visitor_type, y = daily_visits,
           fill = visitor_type)) +
    geom_col() +
    facet_wrap(~restore_loc,
               scales = "free_y",
               ncol   = 5,
               nrow   = 2) +
    scale_fill_viridis_d() +
    labs(x        = "Type of visitor",
         y        = "Number of Visits",
         title    = "Total Number of Visits to Delta Restoration Areas",
         subtitle = "Sum of all visits during study period") +
    theme_bw() +
    theme(legend.position = "bottom",
          axis.ticks.x    = element_blank(),
          axis.text.x     = element_blank())

facet_plot
```


```{r}
ggplotly(facet_plot, tooltip = c('x', 'y'))
```

## Interactive Table

```{r}
DT::datatable(
  daily_visits_long,
  caption  = "Daily visitor counts at Delta restoration sites",
  colnames = c("Location", "Date", "Visitor type", "Daily visits"),
  options  = list(pageLength = 10)
)
```

## Interactive Map

```{r}
restoration_sites <- delta_visits_raw %>%
  janitor::clean_names() %>%
  distinct(restore_loc = eco_restore_approximate_location,
           latitude, longitude) %>%
  drop_na(latitude, longitude)

leaflet(restoration_sites) %>%
  addTiles() %>%
  addMarkers(
    lng   = ~longitude,
    lat   = ~latitude,
    popup = ~restore_loc
  )
```
